### ISSUE TITLE
.bin file is provided but .safetensors file is expected

### ISSUE THREAD

**Issue by YuGuilliman** [ICTMCG/Make-Your-Anchor#14]
Thank you for your help! I am now trying to use my own head.png and body.png as promt images to generate a new video. Following your guidance, I downloaded the pre-trained weights and placed them in ./train/checkpoints. Then I tried running bash train_body.sh, but encountered the following bug report. As I am new to this area, I am not sure what to do next. Could you please give me some advice?

![image](https://github.com/user-attachments/assets/6af6d9d7-2a7e-4619-8ad4-d85976e3fa36)

**Comment by YuGuilliman** [comment]
![image](https://github.com/user-attachments/assets/d56b5b01-962e-4740-b594-5434cf5ce526)

**Comment by YuGuilliman** [comment]
@bone-11 Could you please give me some advice?

**Comment by bone-11** [comment]
This is likely due to the version of diffusers being used; you could try switching to a different version to see if it resolves the issue.

**Comment by YuGuilliman** [comment]
Thank you for your advice, I will have a check. I found that this bug actually do not harm the video generation.
