### ISSUE TITLE
'promt' is not found

### ISSUE THREAD

**Issue by YuGuilliman** [ICTMCG/Make-Your-Anchor#15]
Hi，

I am now tring to generate a new vedio with my own body.png and head.png. When I tried bash train_body.sh, I encountered the following error:
![image](https://github.com/user-attachments/assets/a829f803-5384-45d1-b894-2d25de8a928d)
what should I do? Could you please give me some advice that even a newbie can understand?

**Comment by YuGuilliman** [comment]
I wonder if it is used for identity ?

**Comment by YuGuilliman** [comment]
@bone-11  some advice plz

**Comment by bone-11** [comment]
The variable should no longer be effective. Give me a moment to update the script.

**Comment by bone-11** [comment]
I have fixed the issue; please check if there are any other problems.
