### ISSUE TITLE
not able to generate all.pkl

### ISSUE THREAD

**Issue by vibhu-raturi** [ICTMCG/Make-Your-Anchor#22]
trying to execute stage1_main.py but not able to generate all.pkl. The script stops in between. This condition op_valid_flag.sum() == 0 stops it and if i ignore it it then stops at bracket[low_pos] out of range when optimizing. What can be done

**Comment by bone-11** [comment]
This is an issue with SHOW. op_valid_flag.sum()==0 when the OpenPose is not applied to input videos, and there should be another error information before this line.  You can check the whole log and may find the specific error.

**Comment by vibhu-raturi** [comment]
yes correct, i was able to resolve and generate mesh from my videos. Now i will prepare the data for model training. Just one last question I ran TALKSHOW on demo and generated mesh video, now do I have to train that model also for my custom video or can I use the demo mesh generated from my audio as an input to model which will be trained here

**Comment by bone-11** [comment]
> yes correct, i was able to resolve and generate mesh from my videos. Now i will prepare the data for model training. Just one last question I ran TALKSHOW on demo and generated mesh video, now do I have to train that model also for my custom video or can I use the demo mesh generated from my audio as an input to model which will be trained here

It is better to fine-tune for the custom video, but using the pre-trained model is ok. Besides, you may need to pay attention to the differences in parameters representing the appearance of individuals in SMPL-X.

**Comment by vibhu-raturi** [comment]
okay got it, i will try with pretrained TALKSHOW model first. the mesh you used have black background, do we need to change the background from the existing mesh?, i have white solid background in mesh, secondly for model training default epochs are 60, are they enough for body and head models, my custom video duration is approx 4.10 mins.

**Comment by bone-11** [comment]
> okay got it, i will try with pretrained TALKSHOW model first. the mesh you used have black background, do we need to change the background from the existing mesh?, i have white solid background in mesh, secondly for model training default epochs are 60, are they enough for body and head models, my custom video duration is approx 4.10 mins.

My mesh condition is a black background, maybe you should change it.

**Comment by vibhu-raturi** [comment]
which script needs modification for black background

**Comment by bone-11** [comment]
I just realized that you're using a mesh with a white background as the condition for training. If you train Make-Your-Anchor with a mesh that has a white background, then there should be no need to modify the background.

**Comment by vibhu-raturi** [comment]
white background as in the video used for training has a white wall in the background of the person speaking, is it okay or do i have to make the background either 0 or 255?

**Comment by vibhu-raturi** [comment]
Was able to resolve the background issue. Thanks
