### ISSUE TITLE
How does the pre-trained weights work on a single person, like Seth？

### ISSUE THREAD

**Issue by shengyuting** [ICTMCG/Make-Your-Anchor#8]
Thank you for your great work. I have trained  the model by the open dataset which described in the paper. However, in my test results, the image texture is not clear. Whether it can be greatly improved by fine-tuning training or there is no such problem in your test results？ Looking forward to your reply very much！！！

**Comment by bone-11** [comment]
Thank you for your attention!
The pre-trained weight indeed generates unclear image texture, which can be attributed to training on various appearances leading the model to learn mean features. In our work, fine-tuning on specific appearances can effectively enhance the quality of the appearance. Furthermore, hyperparameter settings, such as CFG and controlnet weight, also impact the results.

**Comment by andrewkuo** [comment]
Thanks for your work! Relating to this, do you have any timeline for when you will release the training and preprocessing code?

**Comment by bone-11** [comment]
Thanks for your interest. I'm trying my best to release the relevant code and pretrained weights within this month.

**Comment by nerlfield** [comment]
Hi, thank you for this great work! I wanted to ask if there are any updates on the training and fine-tuning code release?

**Comment by kike-0304** [comment]
> Thanks for your interest. I'm trying my best to release the relevant code and pretrained weights within this month.

When will you open source？
