### ISSUE TITLE
body/unet/diffusion_pytorch_model.safetensors contains nan value

### ISSUE THREAD

**Issue by ZivKidd** [ICTMCG/Make-Your-Anchor#9]
very impressive job!
I download the checkpoints and code for inference, and the output image of inference/inference_body.py is all black. I found the reason is that the body/unet/diffusion_pytorch_model.safetensors contains nan value. my test code is below.

```python
import torch
from safetensors import safe_open
import os

model_file='inference/checkpoints/seth/body/unet/diffusion_pytorch_model.safetensors'
print('Loading model from', model_file)
os.system('md5sum %s'%model_file)

state_dict = {}
with safe_open(model_file, framework='pt', device='cpu') as f:
    for k in f.keys():
        state_dict[k] = f.get_tensor(k)
# print(state_dict['mid_block.resnets.0.conv2.weight'].max())
for key in state_dict.keys():
    if torch.isnan(state_dict[key].max()):
        print(key, state_dict[key].max())
```

outputs:

Loading model from inference/checkpoints/seth/body/unet/diffusion_pytorch_model.safetensors
524154f3e10ce1024e544783f0b4886f  inference/checkpoints/seth/body/unet/diffusion_pytorch_model.safetensors
mid_block.resnets.0.conv2.weight tensor(nan)

**Comment by bone-11** [comment]
I'm not sure about the cause of this issue. Perhaps you could try using the weight files I uploaded on [OneDrive](https://1drv.ms/f/c/64d71f39113d98e4/ErwtLq-VEYpIj8BeaU5rQT8BURftZlJPud1wDqVlS0W4uQ?e=Pvrko2).
